### ISSUE TITLE
KeyError: 178

### ISSUE THREAD

**Issue by shivamsaboo17** [limingwu8/Image-Registration#4]
else:
--> 124             img_new_value = slice[img_position]

Hi I am getting this error while deforming celebA image. I am opening the image in PIL and using convert('L') and passing numpy array to deforme function.
This is working for emoji but not for my current dataset.

**Comment by shivamsaboo17** [comment]
okay I got it. You are expecting sqare input. How can I modify the code to use it for rectangular images?

**Comment by limingwu8** [comment]
Hi!, I don't really remember the requirement for the input dimension. You probably need to modify the algorithms regarding this function.
